-- AlterTable
ALTER TABLE `Property`
  ADD COLUMN `password` VARCHAR(191) NULL,
  ADD COLUMN `prevReading` DOUBLE NULL,
  ADD COLUMN `currReading` DOUBLE NULL,
  ADD COLUMN `m1Prev` DOUBLE NULL,
  ADD COLUMN `m1Curr` DOUBLE NULL,
  ADD COLUMN `m2Prev` DOUBLE NULL,
  ADD COLUMN `m2Curr` DOUBLE NULL,
  ADD COLUMN `m3Prev` DOUBLE NULL,
  ADD COLUMN `m3Curr` DOUBLE NULL;
